"""Embedded HTML interface for the Nashr editorial workspace."""

NASHR_CONSOLE_HTML = '''<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Nashr — مساحة العمل</title><script src="https://cdn.tailwindcss.com"></script>
<style>
  body{font-family:ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}
  .step{transition:all .2s ease}.step.active{border-color:#4f46e5;background:#eef2ff}.step.done{border-color:#10b981;background:#ecfdf5}
  .drop-zone{transition:all .2s ease}.drop-zone.dragging,.drop-zone:focus-within{border-color:#4f46e5;background:#eef2ff}
  .material-card{transition:transform .15s ease,box-shadow .15s ease,border-color .15s ease}.material-card:hover{transform:translateY(-1px);box-shadow:0 8px 20px rgb(15 23 42 / .08)}
</style>
</head>
<body class="min-h-screen bg-slate-50 text-slate-900">
<main class="mx-auto max-w-6xl px-4 py-8 sm:py-12">
<header class="mb-8 flex flex-wrap items-start justify-between gap-4 border-b pb-6">
  <div><p class="text-sm font-semibold text-indigo-600">Nashr — مساحة العمل</p>
    <h1 class="mt-1 text-3xl font-bold tracking-tight">مكتبة الكتب والمخزون التحريري</h1>
    <p class="mt-2 max-w-2xl text-sm leading-7 text-slate-600">أضف كتابًا، راقب تحليله، ثم اختر مادة وحوّلها إلى مسودة قابلة للمراجعة والنشر.</p>
  </div>
  <nav class="flex gap-2 text-sm" aria-label="التنقل الرئيسي"><span class="rounded-full bg-indigo-50 px-3 py-2 font-semibold text-indigo-700">المكتبة</span><a href="/benchmark" class="rounded-full bg-white px-3 py-2 font-semibold text-slate-600 shadow-sm hover:text-indigo-600">مختبر الجودة</a></nav>
</header>

<section class="mb-6 grid gap-3 sm:grid-cols-3" aria-label="مراحل العمل">
  <div id="step-1" class="step active rounded-2xl border-2 p-4"><p class="text-xs font-bold text-indigo-600">01</p><p class="mt-1 font-bold">أضف كتابًا</p><p class="mt-1 text-xs text-slate-500">اختر كتابًا جديدًا أو محفوظًا</p></div>
  <div id="step-2" class="step rounded-2xl border-2 border-slate-200 bg-white p-4"><p class="text-xs font-bold text-slate-400">02</p><p class="mt-1 font-bold">افهم الكتاب</p><p class="mt-1 text-xs text-slate-500">تابع المحاور والمواد المكتشفة</p></div>
  <div id="step-3" class="step rounded-2xl border-2 border-slate-200 bg-white p-4"><p class="text-xs font-bold text-slate-400">03</p><p class="mt-1 font-bold">حرّر وانشر</p><p class="mt-1 text-xs text-slate-500">أنشئ مسودة وراجعها قبل النشر</p></div>
</section>

<section id="post-bank-section" class="mb-8 rounded-3xl border bg-white p-5 shadow-sm sm:p-7" aria-labelledby="post-bank-heading">
  <div class="flex flex-wrap items-start justify-between gap-4">
    <div><p class="text-xs font-bold text-indigo-600">Post Bank</p><h2 id="post-bank-heading" class="mt-1 text-2xl font-bold">المخزون التحريري</h2>
      <p class="mt-2 max-w-3xl text-sm leading-7 text-slate-600">تصفح المنشورات الناتجة، صفِّها، افتح أصلها، وعدّل النص المحرر دون إعادة تشغيل الإنتاج.</p></div>
    <span id="post-selection-count" class="rounded-full bg-indigo-50 px-3 py-1.5 text-xs font-semibold text-indigo-700">0 محدد</span>
  </div>
  <div class="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-5">
    <input id="post-search" type="search" placeholder="ابحث في العنوان أو المحتوى..." class="rounded-xl border bg-slate-50 p-3 text-sm xl:col-span-2">
    <select id="post-source" class="rounded-xl border bg-slate-50 p-3 text-sm"><option value="">كل الكتب</option></select>
    <select id="post-topic" class="rounded-xl border bg-slate-50 p-3 text-sm"><option value="">كل المحاور</option></select>
    <select id="post-status" class="rounded-xl border bg-slate-50 p-3 text-sm"><option value="">كل الحالات</option><option value="DRAFT">DRAFT</option></select>
  </div>
  <div class="mt-3 flex flex-wrap items-center justify-between gap-3 text-xs text-slate-500">
    <span id="post-bank-summary">جارٍ التحميل...</span>
    <div class="flex gap-2"><button id="post-clear-filters" class="rounded-lg border px-3 py-2 font-semibold hover:border-indigo-400">مسح التصفية</button><button id="post-refresh" class="rounded-lg border px-3 py-2 font-semibold hover:border-indigo-400">تحديث</button></div>
  </div>
  <div id="post-bank-grid" class="mt-5 grid gap-4 lg:grid-cols-2"></div>
  <div id="post-bank-empty" class="mt-5 hidden rounded-2xl border border-dashed bg-slate-50 p-8 text-center"><p class="font-bold">لا توجد Posts مطابقة</p><p class="mt-1 text-sm text-slate-500">جرّب تغيير الفلاتر أو أنشئ Posts عبر Production Job.</p></div>
  <div class="mt-5 flex items-center justify-between"><button id="post-prev" class="rounded-xl border px-4 py-2 text-sm font-semibold disabled:opacity-40">السابق</button><span id="post-page" class="text-xs text-slate-500"></span><button id="post-next" class="rounded-xl border px-4 py-2 text-sm font-semibold disabled:opacity-40">التالي</button></div>
</section>
<section id="post-editor" class="fixed inset-0 z-50 hidden grid place-items-center bg-slate-900/50 p-4">
  <div class="w-full max-w-3xl rounded-3xl bg-white p-5 shadow-2xl sm:p-7">
    <div class="flex items-start justify-between gap-4"><div><p class="text-xs font-bold text-indigo-600">تحرير Post</p><h2 id="post-editor-title" class="mt-1 text-xl font-bold"></h2><p id="post-editor-provenance" class="mt-1 text-xs text-slate-500"></p></div><button id="post-editor-close" class="rounded-xl border px-3 py-2 text-sm">إغلاق</button></div>
    <textarea id="post-editor-content" dir="rtl" class="mt-5 min-h-[300px] w-full rounded-2xl border p-4 leading-8"></textarea>
    <div class="mt-4 flex items-center justify-between gap-3"><span id="post-editor-error" class="text-sm text-red-600"></span><button id="post-editor-save" class="rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white hover:bg-indigo-700">حفظ</button></div>
  </div>
</section>
<section class="rounded-3xl border bg-white p-5 shadow-sm sm:p-7" aria-labelledby="source-heading">
  <div class="mb-5"><h2 id="source-heading" class="text-xl font-bold">ابدأ من مكتبتك</h2><p class="mt-1 text-sm text-slate-500">يمكنك متابعة كتاب محفوظ أو إضافة كتاب PDF جديد.</p></div>
  <div class="grid gap-6 lg:grid-cols-2">
    <div><label for="source-select" class="mb-2 block text-sm font-bold">اختر كتابًا محفوظًا</label>
      <div class="flex gap-2"><select id="source-select" aria-describedby="source-help" class="min-w-0 flex-1 rounded-xl border bg-slate-50 p-3 text-sm"></select><button id="source-btn" class="rounded-xl bg-slate-800 px-5 py-3 font-semibold text-white transition hover:bg-slate-700 disabled:cursor-not-allowed disabled:opacity-50">فتح مساحة الكتاب</button></div>
      <p id="source-help" class="mt-2 text-xs text-slate-500">اختر كتابًا لمعرفة حالته ومتابعة تحليله.</p>
    </div>
    <div><label for="pdf-file" class="mb-2 block text-sm font-bold">أضف كتابًا جديدًا</label>
      <div id="drop-zone" tabindex="0" class="drop-zone cursor-pointer rounded-2xl border-2 border-dashed border-slate-300 bg-slate-50 p-4 text-center">
        <input id="pdf-file" type="file" accept="application/pdf" class="sr-only">
        <p class="font-semibold text-slate-700">اسحب ملف PDF هنا</p><p class="mt-1 text-xs text-slate-500">أو اضغط لاختيار ملف من جهازك — الحد الأقصى 100 MB</p>
        <p id="file-name" class="mt-3 hidden rounded-lg bg-white px-3 py-2 text-xs font-semibold text-indigo-700"></p>
      </div><button id="upload-btn" class="mt-3 w-full rounded-xl bg-indigo-600 px-5 py-3 font-semibold text-white transition hover:bg-indigo-700 disabled:cursor-not-allowed disabled:opacity-50">رفع وتحليل الكتاب</button>
    </div>
  </div>
  <div id="empty-library" class="mt-6 hidden rounded-2xl border border-dashed bg-slate-50 p-6 text-center"><p class="font-bold">لم تضف أي كتاب بعد</p><p class="mt-1 text-sm text-slate-500">ابدأ برفع ملف PDF من المنطقة أعلاه.</p></div>
  <div id="progress" class="mt-6 hidden rounded-2xl border border-indigo-100 bg-indigo-50 p-4" role="status" aria-live="polite"><div class="flex items-center justify-between gap-4"><span id="progress-message" class="text-sm font-semibold text-indigo-900"></span><span id="progress-percent" class="text-xs font-bold text-indigo-700"></span></div><div class="mt-3 h-2 overflow-hidden rounded-full bg-indigo-100"><div id="progress-bar" class="h-full rounded-full bg-indigo-600 transition-all" style="width:0%"></div></div></div>
  <div id="error" class="mt-4 hidden rounded-2xl border border-red-200 bg-red-50 p-4 text-sm leading-7 text-red-700" role="alert"></div>
  <div id="retry-box" class="mt-4 hidden rounded-2xl border border-amber-200 bg-amber-50 p-4"><p class="text-sm font-semibold text-amber-900">توقف التحليل قبل اكتماله.</p><p class="mt-1 text-xs text-amber-800">تم الاحتفاظ بالكتاب ويمكنك إعادة المحاولة دون رفعه من جديد.</p><button id="retry-btn" class="mt-3 rounded-xl bg-amber-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-amber-700">إعادة المحاولة</button></div>
</section>

<section id="book-section" class="mt-8 hidden" aria-labelledby="book-title">
  <div class="rounded-3xl border bg-white p-5 shadow-sm sm:p-7"><div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-xs font-bold text-indigo-600">مساحة الكتاب</p><h2 id="book-title" class="mt-1 text-2xl font-bold"></h2><p id="book-description" class="mt-2 max-w-3xl text-sm leading-7 text-slate-600"></p></div><button id="refresh-btn" class="rounded-xl border px-4 py-2 text-sm font-semibold text-slate-600 hover:border-indigo-400 hover:text-indigo-600">تحديث الحالة</button></div><div class="mt-5 flex flex-wrap gap-2 text-xs"><span id="topic-count" class="rounded-full bg-slate-100 px-3 py-1.5"></span><span id="material-count" class="rounded-full bg-slate-100 px-3 py-1.5"></span><span id="book-status" class="rounded-full bg-slate-100 px-3 py-1.5"></span></div></div>
  <div id="material-toolbar" class="mt-5 hidden rounded-2xl border bg-white p-4 shadow-sm"><div class="flex flex-col gap-3 lg:flex-row lg:items-center"><label class="min-w-0 flex-1"><span class="sr-only">البحث في المواد</span><input id="material-search" type="search" placeholder="ابحث في العناوين والمحتوى..." class="w-full rounded-xl border bg-slate-50 p-3 text-sm"></label><select id="material-kind" class="rounded-xl border bg-slate-50 p-3 text-sm"><option value="">كل التصنيفات</option></select><select id="material-sort" class="rounded-xl border bg-slate-50 p-3 text-sm"><option value="position">الترتيب الأصلي</option><option value="title">العنوان: أ - ي</option><option value="kind">التصنيف</option></select><button id="collapse-topics" class="rounded-xl border px-4 py-3 text-sm font-semibold text-slate-600 hover:border-indigo-400 hover:text-indigo-600">طيّ المحاور</button></div><div class="mt-3 flex items-center justify-between text-xs text-slate-500"><span id="material-result-count"></span><button id="clear-material-filters" class="font-semibold text-indigo-600 hover:underline">مسح التصفية</button></div></div>
  <div id="topics" class="mt-5 space-y-4"></div><div id="topics-empty" class="mt-5 hidden rounded-2xl border border-dashed bg-white p-8 text-center"><p class="font-bold">لم تظهر مواد بعد</p><p class="mt-1 text-sm text-slate-500">ستظهر المحاور والمواد هنا تدريجيًا أثناء التحليل.</p></div><div id="filtered-empty" class="mt-5 hidden rounded-2xl border border-dashed bg-white p-8 text-center"><p class="font-bold">لا توجد نتائج مطابقة</p><p class="mt-1 text-sm text-slate-500">جرّب تغيير البحث أو التصنيف أو الترتيب.</p></div>
</section>

<section id="draft-section" class="fixed inset-0 z-40 hidden grid place-items-center overflow-y-auto overscroll-contain bg-slate-900/40 p-3 sm:p-10" aria-labelledby="draft-heading"><div class="mx-auto max-h-[calc(100dvh-1.5rem)] w-full max-w-3xl overflow-y-auto rounded-3xl border border-indigo-200 bg-indigo-50 p-4 shadow-2xl sm:max-h-[calc(100dvh-5rem)] sm:p-7"><div class="flex items-start justify-between gap-4"><div><p class="text-xs font-bold text-indigo-700">التحرير والنشر</p><h2 id="draft-heading" class="mt-1 text-xl font-bold">مسودة المادة المختارة</h2><p class="mt-1 text-sm leading-6 text-slate-600">راجع النص وعدّله قبل إرساله إلى تيليجرام. يمكنك الإغلاق والعودة إلى نفس موضع القائمة.</p></div><button id="close-draft-btn" class="shrink-0 rounded-xl border bg-white px-3 py-2 text-sm font-semibold text-slate-600 hover:border-indigo-400" aria-label="إغلاق المحرر">إغلاق</button></div><textarea id="draft-content" dir="rtl" aria-label="محتوى المسودة" class="mt-4 min-h-[220px] w-full rounded-2xl border bg-white p-4 leading-8 shadow-sm sm:min-h-80"></textarea><button id="publish-btn" class="mt-4 w-full rounded-xl bg-emerald-600 px-5 py-3.5 font-bold text-white transition hover:bg-emerald-700 disabled:cursor-not-allowed disabled:opacity-50 sm:py-4">نشر بعد المراجعة في تيليجرام</button></div></section>
<section id="success-section" class="mt-8 hidden rounded-2xl border border-emerald-200 bg-emerald-50 p-5" role="status"><h2 class="text-xl font-bold text-emerald-800">تم النشر بنجاح</h2><p class="mt-2 text-sm text-emerald-700">تم إرسال المسودة إلى تيليجرام. رقم الرسالة:</p><code id="external-id" class="mt-2 block rounded-lg bg-white p-2"></code></section>
</main>
<script>
const $=id=>document.getElementById(id);const state={sourceId:null,jobId:null,publicationId:null,pollTimer:null,selectedPostIds:[],postOffset:0,postTotal:0};
async function loadPostSources(){const sources=await request('/sources');$('post-source').innerHTML='<option value="">كل الكتب</option>'+sources.map(s=>'<option value="'+esc(s.id)+'">'+esc(s.book_title||s.filename)+'</option>').join('');}
async function loadPostTopics(sourceId){$('post-topic').innerHTML='<option value="">كل المحاور</option>';if(!sourceId)return;try{const d=await request('/sources/'+sourceId+'/book-map');$('post-topic').innerHTML='<option value="">كل المحاور</option>'+d.topics.map(t=>'<option value="'+esc(t.id)+'">'+esc(t.title)+'</option>').join('');}catch(e){}}
function selectedPost(id){return state.selectedPostIds.includes(id)}
function togglePostSelection(id){if(selectedPost(id))state.selectedPostIds=state.selectedPostIds.filter(x=>x!==id);else state.selectedPostIds.push(id);renderSelectionCount();}
function renderSelectionCount(){$('post-selection-count').textContent=state.selectedPostIds.length+' محدد';window.nashrPostSelection=()=>[...state.selectedPostIds];}
function renderPostBank(d){state.postTotal=d.total;const grid=$('post-bank-grid');grid.innerHTML=d.items.map(p=>'<article class="rounded-2xl border p-4 '+(selectedPost(p.post_id)?'border-indigo-400 bg-indigo-50':'bg-white')+'"><div class="flex items-start justify-between gap-3"><label class="flex items-start gap-3"><input type="checkbox" '+(selectedPost(p.post_id)?'checked':'')+' data-select-post="'+esc(p.post_id)+'" class="mt-1 h-4 w-4"><span><h3 class="font-bold">'+esc(p.title)+'</h3><p class="mt-1 text-xs text-slate-500">'+esc(p.topic_title||'بدون محور')+' · '+esc(p.source_title)+'</p></span></label><span class="rounded-full bg-slate-100 px-2 py-1 text-[11px]">'+esc(p.status)+(p.published?' · منشور':'')+'</span></div><p class="mt-3 line-clamp-4 text-sm leading-7 text-slate-700">'+esc(p.content_preview)+'</p><div class="mt-3 flex items-center justify-between gap-3 text-xs text-slate-400"><span>المادة: '+esc(p.knowledge_unit_id.slice(0,8))+'…</span><div class="flex gap-2"><button data-open-post="'+esc(p.post_id)+'" class="rounded-lg border px-3 py-1.5 font-semibold text-slate-700 hover:border-indigo-400">معاينة/تحرير</button></div></div></article>').join('');
document.querySelectorAll('[data-select-post]').forEach(el=>el.onchange=()=>{togglePostSelection(el.dataset.selectPost);loadPostBank();});
document.querySelectorAll('[data-open-post]').forEach(el=>el.onclick=()=>openPostEditor(el.dataset.openPost));
$('post-bank-empty').classList.toggle('hidden',d.items.length>0);
$('post-bank-summary').textContent=d.total+' Posts · '+d.items.length+' معروضة';
const page=Math.floor(d.offset/d.limit)+1;const pages=Math.max(1,Math.ceil(d.total/d.limit));$('post-page').textContent='صفحة '+page+' من '+pages;
$('post-prev').disabled=d.offset===0;$('post-next').disabled=d.offset+d.limit>=d.total;renderSelectionCount();}
async function loadPostBank(){const params=new URLSearchParams();const source=$('post-source').value,topic=$('post-topic').value,status=$('post-status').value,q=$('post-search').value.trim();if(source)params.set('source_id',source);if(topic)params.set('topic_id',topic);if(status)params.set('status',status);if(q)params.set('q',q);params.set('limit','50');params.set('offset',String(state.postOffset));try{renderPostBank(await request('/posts?'+params.toString()));}catch(e){$('post-bank-summary').textContent=e.message;}}
async function openPostEditor(id){try{const p=await request('/posts/'+id);$('post-editor-title').textContent=p.title;$('post-editor-provenance').textContent=(p.source_title||'المصدر')+' ← '+(p.topic_title||'بدون محور')+' ← '+(p.title||'المادة');$('post-editor-content').value=p.content;$('post-editor').dataset.postId=id;$('post-editor-error').textContent='';$('post-editor').classList.remove('hidden');}catch(e){alert(e.message);}}
async function savePost(){const id=$('post-editor').dataset.postId,content=$('post-editor-content').value.trim();if(!content){$('post-editor-error').textContent='المحتوى لا يمكن أن يكون فارغًا.';return;}$('post-editor-save').disabled=true;try{await request('/posts/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({content})});$('post-editor').classList.add('hidden');await loadPostBank();}catch(e){$('post-editor-error').textContent=e.message;}finally{$('post-editor-save').disabled=false;}}

function setStage(stage){for(let i=1;i<=3;i++){const el=$('step-'+i);el.classList.remove('active','done');if(i<stage)el.classList.add('done');if(i===stage)el.classList.add('active');}}
function setBusy(v){$('upload-btn').disabled=v;$('source-btn').disabled=v;$('retry-btn').disabled=v;$('publish-btn').disabled=v;}
function showProgress(message,done=0,total=0){$('progress').classList.remove('hidden');$('progress-message').textContent=message||'';const pct=total?Math.min(100,Math.round(done/total*100)):0;$('progress-percent').textContent=total?`${pct}%`:'';$('progress-bar').style.width=(total?pct:25)+'%';}
function hideProgress(){$('progress').classList.add('hidden');}
function showError(message){$('error').textContent=message;$('error').classList.remove('hidden');}
function clearError(){$('error').classList.add('hidden');$('retry-box').classList.add('hidden');}
function esc(t){return(t??'').toString().replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
async function request(url,opt={}){const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||'تعذر تنفيذ العملية.');return d;}
function stageLabel(stage){return({QUEUED:'في قائمة الانتظار',PREPARING_DOCUMENT:'جاري تجهيز وثيقة الكتاب',BUILDING_BOOK_MAP:'جاري بناء خريطة الكتاب',DISCOVERING_MATERIALS:'جاري اكتشاف المواد داخل المحاور',FINALIZING:'جاري إنهاء المخزون',COMPLETED:'اكتمل تحليل الكتاب'}[stage]||stage||'جاري تحليل الكتاب');}
async function loadSources(){const sources=await request('/sources');const select=$('source-select');select.innerHTML='<option value="">اختر كتابًا محفوظًا...</option>'+sources.map(s=>'<option value="'+esc(s.id)+'">'+esc(s.book_title||s.filename)+'</option>').join('');$('empty-library').classList.toggle('hidden',sources.length>0);$('source-btn').disabled=!sources.length;}
function renderBook(d){$('book-title').textContent=d.book.title;$('book-description').textContent=d.book.description||'لا يوجد وصف متاح لهذا الكتاب بعد.';$('topic-count').textContent=d.topics.length+' محاور';$('material-count').textContent=d.count+' مواد';$('book-status').textContent=d.job?('الحالة: '+stageLabel(d.job.stage||d.job.status)):'جاهز للمراجعة';$('book-section').classList.remove('hidden');const kinds=new Set();const html=d.topics.map(t=>{const mats=t.materials.map(m=>{kinds.add(m.kind||'مادة');return '<button data-id="'+esc(m.id)+'" data-title="'+esc(m.title)+'" data-kind="'+esc(m.kind||'مادة')+'" data-content="'+esc(m.content)+'" data-position="'+m.position+'" class="material-card text-right rounded-2xl border bg-white p-4 hover:border-indigo-400"><div class="flex justify-between gap-3"><strong class="text-sm">'+esc(m.title)+'</strong><span class="text-xs text-slate-400">'+esc(m.kind||'مادة')+'</span></div><p class="mt-2 line-clamp-3 text-xs leading-6 text-slate-600">'+esc(m.content)+'</p><p class="mt-2 text-xs text-slate-400">'+esc(m.source_reference||'مرجع غير محدد')+'</p></button>';}).join('');return'<article data-topic class="rounded-2xl border bg-white p-5 shadow-sm"><button data-collapse class="flex w-full items-start justify-between gap-4 text-right"><div><p class="text-xs text-slate-400">المحور '+t.position+'</p><h3 class="mt-1 text-lg font-bold">'+esc(t.title)+'</h3><p class="mt-1 text-sm leading-6 text-slate-600">'+esc(t.description)+'</p></div><div class="text-left"><span class="rounded-full bg-indigo-50 px-3 py-1 text-xs text-indigo-700">'+t.materials.length+' مواد</span><p class="mt-2 text-xs text-slate-400">'+esc(t.discovery_status||'قيد التجهيز')+'</p></div></button><div data-topic-content class="mt-4 grid gap-3">'+(mats||'<p class="text-sm text-slate-400">لم تُكتشف مواد في هذا المحور حتى الآن.</p>')+'</div></article>';}).join('');$('topics').innerHTML=html;$('topics-empty').classList.toggle('hidden',d.topics.length>0);$('material-toolbar').classList.toggle('hidden',d.count===0);document.querySelectorAll('.material-card').forEach(b=>b.onclick=()=>selectMaterial(b.dataset.id));document.querySelectorAll('[data-collapse]').forEach(b=>b.onclick=()=>b.parentElement.querySelector('[data-topic-content]').classList.toggle('hidden'));populateKinds(kinds);applyMaterialFilters();}
function populateKinds(kinds){const select=$('material-kind');const current=select.value;select.innerHTML='<option value="">كل التصنيفات</option>'+Array.from(kinds).sort((a,b)=>a.localeCompare(b,'ar')).map(k=>'<option value="'+esc(k)+'">'+esc(k)+'</option>').join('');select.value=current;}
function applyMaterialFilters(){const query=$('material-search').value.trim().toLocaleLowerCase('ar');const kind=$('material-kind').value;const sort=$('material-sort').value;const cards=Array.from(document.querySelectorAll('.material-card'));cards.sort((a,b)=>{if(sort==='title')return a.dataset.title.localeCompare(b.dataset.title,'ar');if(sort==='kind')return a.dataset.kind.localeCompare(b.dataset.kind,'ar');return Number(a.dataset.position)-Number(b.dataset.position);});cards.forEach(card=>card.parentElement.appendChild(card));let visible=0;cards.forEach(card=>{const hay=(card.dataset.title+' '+card.dataset.content).toLocaleLowerCase('ar');const show=(!query||hay.includes(query))&&(!kind||card.dataset.kind===kind);card.classList.toggle('hidden',!show);if(show)visible++;});document.querySelectorAll('[data-topic]').forEach(topic=>topic.classList.toggle('hidden',topic.querySelectorAll('.material-card:not(.hidden)').length===0));$('material-result-count').textContent=visible+' من '+cards.length+' مواد معروضة';$('filtered-empty').classList.toggle('hidden',visible>0||cards.length===0);}
async function refreshBook(){if(!state.sourceId)return;try{renderBook(await request('/sources/'+state.sourceId+'/book-map'));}catch(e){showError('تعذر تحديث مساحة الكتاب الآن.');}}
async function poll(){if(!state.jobId)return;try{const d=await request('/sources/'+state.sourceId+'/discovery/status');state.jobId=d.job_id||state.jobId;setStage(2);showProgress(stageLabel(d.stage),d.topics_completed||0,d.topics_total||0);await refreshBook();if(d.status==='COMPLETED'){showProgress('اكتمل تحليل الكتاب. الخريطة والمخزون جاهزان.',d.topics_total||1,d.topics_total||1);setBusy(false);return;}if(d.status==='FAILED'){setBusy(false);$('retry-box').classList.toggle('hidden',!d.retryable);showError('تعذر إكمال تحليل الكتاب. '+(d.error||'يمكنك إعادة المحاولة الآن.'));return;}state.pollTimer=setTimeout(poll,2000);}catch(e){setBusy(false);showError(e.message);}}
async function startDiscovery(sourceId){clearError();state.sourceId=sourceId;state.jobId=null;$('draft-section').classList.add('hidden');$('success-section').classList.add('hidden');setStage(2);setBusy(true);showProgress('جاري بدء تحليل الكتاب...');try{const d=await request('/sources/'+sourceId+'/discovery',{method:'POST'});state.jobId=d.job_id;showProgress(stageLabel(d.stage),0,d.topics_total||0);await refreshBook();poll();}catch(e){setBusy(false);showError(e.message);}}
async function selectMaterial(id){clearError();setStage(3);setBusy(true);showProgress('جاري إنشاء المسودة...');try{const d=await request('/knowledge-units/'+id+'/draft',{method:'POST'});state.publicationId=d.id;$('draft-content').value=d.content||'';$('draft-section').classList.remove('hidden');document.body.classList.add('overflow-hidden');hideProgress();}catch(e){showError(e.message);}finally{setBusy(false);}}
$('source-select').onchange=()=>{clearError();if($('source-select').value)setStage(2);else setStage(1);};$('source-btn').onclick=()=>{const id=$('source-select').value;if(!id)return showError('اختر كتابًا محفوظًا أولًا.');startDiscovery(id);};
$('drop-zone').onclick=()=> $('pdf-file').click();$('drop-zone').onkeydown=e=>{if(e.key==='Enter'||e.key===' ')$('pdf-file').click();};$('drop-zone').ondragover=e=>{e.preventDefault();$('drop-zone').classList.add('dragging');};$('drop-zone').ondragleave=()=>$('drop-zone').classList.remove('dragging');$('drop-zone').ondrop=e=>{e.preventDefault();$('drop-zone').classList.remove('dragging');if(e.dataTransfer.files.length){$('pdf-file').files=e.dataTransfer.files;$('pdf-file').dispatchEvent(new Event('change'));}};$('pdf-file').onchange=()=>{const file=$('pdf-file').files[0];$('file-name').classList.toggle('hidden',!file);if(file)$('file-name').textContent=file.name+' — '+(file.size/1024/1024).toFixed(1)+' MB';};
$('upload-btn').onclick=async()=>{clearError();const file=$('pdf-file').files[0];if(!file)return showError('اختر ملف PDF أولًا.');if(file.type!=='application/pdf'&&!file.name.toLowerCase().endsWith('.pdf'))return showError('الملف المحدد ليس بصيغة PDF.');if(file.size>100*1024*1024)return showError('حجم الملف يتجاوز الحد الأقصى وهو 100 MB.');setBusy(true);showProgress('جاري رفع الكتاب وحفظه...');try{const form=new FormData();form.append('file',file);const s=await request('/sources',{method:'POST',body:form});await loadSources();$('source-select').value=s.id;startDiscovery(s.id);}catch(e){setBusy(false);showError(e.message);}};
$('retry-btn').onclick=()=>{if(state.sourceId)startRetry();};async function startRetry(){clearError();setBusy(true);showProgress('جاري إعادة تحليل الكتاب...');try{const d=await request('/sources/'+state.sourceId+'/discovery/retry',{method:'POST'});state.jobId=d.job_id;poll();}catch(e){setBusy(false);showError(e.message);}}
$('material-search').oninput=applyMaterialFilters;$('material-kind').onchange=applyMaterialFilters;$('material-sort').onchange=applyMaterialFilters;$('clear-material-filters').onclick=()=>{$('material-search').value='';$('material-kind').value='';$('material-sort').value='position';applyMaterialFilters();};$('collapse-topics').onclick=()=>{const topics=Array.from(document.querySelectorAll('[data-topic-content]'));const shouldOpen=topics.some(x=>!x.classList.contains('hidden'));topics.forEach(x=>x.classList.toggle('hidden',shouldOpen));$('collapse-topics').textContent=shouldOpen?'فتح المحاور':'طيّ المحاور';};$('close-draft-btn').onclick=()=>{$('draft-section').classList.add('hidden');document.body.classList.remove('overflow-hidden');setStage(2);};$('refresh-btn').onclick=refreshBook;$('publish-btn').onclick=async()=>{if(!state.publicationId)return;if(!confirm('هل راجعت المسودة وتريد نشرها الآن في تيليجرام؟'))return;clearError();setBusy(true);showProgress('جاري حفظ المراجعة والنشر في تيليجرام...');try{const d=await request('/publications/'+state.publicationId+'/publish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:$('draft-content').value})});if(d.status!=='PUBLISHED')throw Error(d.error_message||'تعذر تأكيد النشر.');$('external-id').textContent=d.external_id||'غير متاح';$('success-section').classList.remove('hidden');hideProgress();}catch(e){showError(e.message);}finally{setBusy(false);}};
loadPostSources().then(loadPostBank).catch(e=>$('post-bank-summary').textContent=e.message);
$('post-source').onchange=()=>{state.postOffset=0;loadPostTopics($('post-source').value);loadPostBank();};
$('post-topic').onchange=()=>{state.postOffset=0;loadPostBank();};
$('post-status').onchange=()=>{state.postOffset=0;loadPostBank();};
$('post-search').oninput=()=>{clearTimeout(state.postSearchTimer);state.postSearchTimer=setTimeout(()=>{state.postOffset=0;loadPostBank();},300);};
$('post-clear-filters').onclick=()=>{$('post-search').value='';$('post-source').value='';$('post-topic').innerHTML='<option value="">كل المحاور</option>';$('post-status').value='';state.postOffset=0;loadPostBank();};
$('post-refresh').onclick=()=>loadPostBank();
$('post-prev').onclick=()=>{state.postOffset=Math.max(0,state.postOffset-50);loadPostBank();};
$('post-next').onclick=()=>{state.postOffset+=50;loadPostBank();};
$('post-editor-close').onclick=()=>$('post-editor').classList.add('hidden');
$('post-editor-save').onclick=savePost;
renderSelectionCount();
loadSources().catch(e=>showError('تعذر تحميل المكتبة. '+e.message));
</script></body></html>'''
