"""Embedded HTML interface for the Nashr editorial workspace."""

NASHR_CONSOLE_HTML = '''<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Nashr — مساحة العمل</title><script src="https://cdn.tailwindcss.com"></script>
<style>
  body{font-family:ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}
  .step{transition:all .2s ease}.step.active{border-color:#4f46e5;background:#eef2ff}.step.done{border-color:#10b981;background:#ecfdf5}
  .drop-zone{transition:all .2s ease}.drop-zone.dragging,.drop-zone:focus-within{border-color:#4f46e5;background:#eef2ff}
  .material-card{transition:transform .15s ease,box-shadow .15s ease,border-color .15s ease}.material-card:hover{transform:translateY(-1px);box-shadow:0 8px 20px rgb(15 23 42 / .08)}
</style>
</head>
<body class="min-h-screen bg-slate-50 text-slate-900">
<main class="mx-auto max-w-6xl px-4 py-8 sm:py-12">
<header class="mb-8 flex flex-wrap items-start justify-between gap-4 border-b pb-6">
  <div><p class="text-sm font-semibold text-indigo-600">Nashr — مساحة العمل</p>
    <h1 class="mt-1 text-3xl font-bold tracking-tight">مكتبة الكتب والمخزون التحريري</h1>
    <p class="mt-2 max-w-2xl text-sm leading-7 text-slate-600">أضف كتابًا، راقب تحليله، ثم اختر مادة وحوّلها إلى مسودة قابلة للمراجعة والنشر.</p>
  </div>
  <nav class="flex flex-wrap gap-2 text-sm" aria-label="التنقل الرئيسي"><span class="rounded-full bg-indigo-50 px-3 py-2 font-semibold text-indigo-700">📚 المكتبة</span><a href="/posts/workspace" class="rounded-full bg-white px-3 py-2 font-semibold text-slate-600 shadow-sm hover:text-indigo-600">✍️ المنشورات</a><a href="/publishing" class="rounded-full bg-white px-3 py-2 font-semibold text-slate-600 shadow-sm hover:text-indigo-600">📅 النشر</a><a href="/benchmark" class="rounded-full bg-white px-3 py-2 font-semibold text-slate-600 shadow-sm hover:text-indigo-600">مختبر الجودة</a></nav>
</header>

<section class="mb-6 grid gap-3 sm:grid-cols-3" aria-label="رحلة العمل">
  <div id="step-1" class="step active rounded-2xl border-2 p-4"><p class="text-xs font-bold text-indigo-600">01</p><p class="mt-1 font-bold">المكتبة</p><p class="mt-1 text-xs text-slate-500">أضف الكتاب وافهم خريطته ومواده</p></div>
  <a href="/posts/workspace" class="step rounded-2xl border-2 border-slate-200 bg-white p-4 block hover:border-indigo-300"><p class="text-xs font-bold text-slate-400">02</p><p class="mt-1 font-bold">المنشورات</p><p class="mt-1 text-xs text-slate-500">أنشئ Posts، حررها وراجعها واعتمدها</p></a>
  <a href="/publishing" class="step rounded-2xl border-2 border-slate-200 bg-white p-4 block hover:border-indigo-300"><p class="text-xs font-bold text-slate-400">03</p><p class="mt-1 font-bold">الجدولة</p><p class="mt-1 text-xs text-slate-500">رتب المعتمدين وحدد أوقات النشر</p></a>
</section>

<section class="rounded-3xl border bg-white p-5 shadow-sm sm:p-7" aria-labelledby="source-heading">
  <div class="mb-5"><h2 id="source-heading" class="text-xl font-bold">ابدأ من مكتبتك</h2><p class="mt-1 text-sm text-slate-500">يمكنك متابعة كتاب محفوظ أو إضافة كتاب PDF جديد.</p></div>
  <div class="grid gap-6 lg:grid-cols-2">
    <div><label for="source-select" class="mb-2 block text-sm font-bold">اختر كتابًا محفوظًا</label>
      <div class="flex gap-2"><select id="source-select" aria-describedby="source-help" class="min-w-0 flex-1 rounded-xl border bg-slate-50 p-3 text-sm"></select><button id="source-btn" class="rounded-xl bg-slate-800 px-5 py-3 font-semibold text-white transition hover:bg-slate-700 disabled:cursor-not-allowed disabled:opacity-50">فتح الكتاب</button></div>
      <p id="source-help" class="mt-2 text-xs text-slate-500">اختر كتابًا لمعرفة حالته ومتابعة تحليله.</p>
    </div>
    <div><label for="pdf-file" class="mb-2 block text-sm font-bold">أضف كتابًا جديدًا</label>
      <div id="drop-zone" tabindex="0" class="drop-zone cursor-pointer rounded-2xl border-2 border-dashed border-slate-300 bg-slate-50 p-4 text-center">
        <input id="pdf-file" type="file" accept="application/pdf" class="sr-only">
        <p class="font-semibold text-slate-700">اسحب ملف PDF هنا</p><p class="mt-1 text-xs text-slate-500">أو اضغط لاختيار ملف من جهازك — الحد الأقصى 100 MB</p>
        <p id="file-name" class="mt-3 hidden rounded-lg bg-white px-3 py-2 text-xs font-semibold text-indigo-700"></p>
      </div><button id="upload-btn" class="mt-3 w-full rounded-xl bg-indigo-600 px-5 py-3 font-semibold text-white transition hover:bg-indigo-700 disabled:cursor-not-allowed disabled:opacity-50">رفع الكتاب</button>
    </div>
  </div>
  <div id="empty-library" class="mt-6 hidden rounded-2xl border border-dashed bg-slate-50 p-6 text-center"><p class="font-bold">لم تضف أي كتاب بعد</p><p class="mt-1 text-sm text-slate-500">ابدأ برفع ملف PDF من المنطقة أعلاه.</p></div>
  <div id="progress" class="mt-6 hidden rounded-2xl border border-indigo-100 bg-indigo-50 p-4" role="status" aria-live="polite"><div class="flex items-center justify-between gap-4"><span id="progress-message" class="text-sm font-semibold text-indigo-900"></span><span id="progress-percent" class="text-xs font-bold text-indigo-700"></span></div><div class="mt-3 h-2 overflow-hidden rounded-full bg-indigo-100"><div id="progress-bar" class="h-full rounded-full bg-indigo-600 transition-all" style="width:0%"></div></div></div>
  <div id="error" class="mt-4 hidden rounded-2xl border border-red-200 bg-red-50 p-4 text-sm leading-7 text-red-700" role="alert"></div>
  <div id="retry-box" class="mt-4 hidden rounded-2xl border border-amber-200 bg-amber-50 p-4"><p class="text-sm font-semibold text-amber-900">توقف التحليل قبل اكتماله.</p><p class="mt-1 text-xs text-amber-800">تم الاحتفاظ بالكتاب ويمكنك إعادة المحاولة دون رفعه من جديد.</p><button id="retry-btn" class="mt-3 rounded-xl bg-amber-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-amber-700">إعادة المحاولة</button></div>
</section>

<section id="book-section" class="mt-8 hidden" aria-labelledby="book-title">
  <div class="rounded-3xl border bg-white p-5 shadow-sm sm:p-7"><div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-xs font-bold text-indigo-600">مساحة الكتاب</p><h2 id="book-title" class="mt-1 text-2xl font-bold"></h2><p id="book-description" class="mt-2 max-w-3xl text-sm leading-7 text-slate-600"></p></div><div class="flex flex-wrap gap-2"><a href="/posts/workspace" class="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-bold text-white hover:bg-indigo-700">✍️ افتح مصنع المحتوى</a><button id="refresh-btn" class="rounded-xl border px-4 py-2 text-sm font-semibold text-slate-600 hover:border-indigo-400 hover:text-indigo-600">تحديث الحالة</button></div></div><div id="discovery-status" class="mt-5 rounded-2xl border bg-slate-50 p-4" role="status" aria-live="polite"></div><div class="mt-4 flex flex-wrap gap-2"><button id="start-discovery-btn" class="hidden rounded-xl bg-indigo-600 px-4 py-2 text-sm font-bold text-white">▶ بدء تحليل الكتاب</button></div><div class="mt-5 flex flex-wrap gap-2 text-xs"><span id="topic-count" class="rounded-full bg-slate-100 px-3 py-1.5"></span><span id="material-count" class="rounded-full bg-slate-100 px-3 py-1.5"></span><span id="book-status" class="rounded-full bg-slate-100 px-3 py-1.5"></span></div></div>
  <div id="material-toolbar" class="mt-5 hidden rounded-2xl border bg-white p-4 shadow-sm"><div class="flex flex-col gap-3 lg:flex-row lg:items-center"><label class="min-w-0 flex-1"><span class="sr-only">البحث في المواد</span><input id="material-search" type="search" placeholder="ابحث في العناوين والمحتوى..." class="w-full rounded-xl border bg-slate-50 p-3 text-sm"></label><select id="material-kind" class="rounded-xl border bg-slate-50 p-3 text-sm"><option value="">كل التصنيفات</option></select><select id="material-sort" class="rounded-xl border bg-slate-50 p-3 text-sm"><option value="position">الترتيب الأصلي</option><option value="title">العنوان: أ - ي</option><option value="kind">التصنيف</option></select><button id="collapse-topics" class="rounded-xl border px-4 py-3 text-sm font-semibold text-slate-600 hover:border-indigo-400 hover:text-indigo-600">طيّ المحاور</button></div><div class="mt-3 flex items-center justify-between text-xs text-slate-500"><span id="material-result-count"></span><button id="clear-material-filters" class="font-semibold text-indigo-600 hover:underline">مسح التصفية</button></div></div>
  <div id="topics" class="mt-5 space-y-4"></div><div id="topics-empty" class="mt-5 hidden rounded-2xl border border-dashed bg-white p-8 text-center"><p class="font-bold">لم تظهر مواد بعد</p><p class="mt-1 text-sm text-slate-500">ستظهر المحاور والمواد هنا تدريجيًا أثناء التحليل.</p></div><div id="filtered-empty" class="mt-5 hidden rounded-2xl border border-dashed bg-white p-8 text-center"><p class="font-bold">لا توجد نتائج مطابقة</p><p class="mt-1 text-sm text-slate-500">جرّب تغيير البحث أو التصنيف أو الترتيب.</p></div>
</section>

</main>
<script>
const $=id=>document.getElementById(id);const state={sourceId:null,jobId:null,pollTimer:null};async function request(url,opt={}){const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||'تعذر تنفيذ العملية.');return d;}function esc(t){return(t??'').toString().replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}function setStage(stage){for(let i=1;i<=3;i++){const el=$('step-'+i);if(!el)continue;el.classList.remove('active','done');if(i<stage)el.classList.add('done');if(i===stage)el.classList.add('active');}}
function setBusy(v){['upload-btn','source-btn','retry-btn','start-discovery-btn'].forEach(id=>{const el=$(id);if(el)el.disabled=v;});}
function showProgress(message,done=0,total=0){$('progress').classList.remove('hidden');$('progress-message').textContent=message||'';const pct=total?Math.min(100,Math.round(done/total*100)):0;$('progress-percent').textContent=total?`${pct}%`:'';$('progress-bar').style.width=(total?pct:25)+'%';}
function hideProgress(){$('progress').classList.add('hidden');}
function showError(message){$('error').textContent=message;$('error').classList.remove('hidden');}
function clearError(){$('error').classList.add('hidden');$('retry-box').classList.add('hidden');}
function esc(t){return(t??'').toString().replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
async function request(url,opt={}){const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||'تعذر تنفيذ العملية.');return d;}
function stageLabel(stage){return({QUEUED:'في قائمة الانتظار',PREPARING_DOCUMENT:'جاري تجهيز وثيقة الكتاب',BUILDING_BOOK_MAP:'جاري بناء خريطة الكتاب',DISCOVERING_MATERIALS:'جاري اكتشاف المواد داخل المحاور',FINALIZING:'جاري إنهاء المخزون',COMPLETED:'اكتمل تحليل الكتاب'}[stage]||stage||'جاري تحليل الكتاب');}
async function loadSources(){const sources=await request('/sources');const select=$('source-select');select.innerHTML='<option value="">اختر كتابًا محفوظًا...</option>'+sources.map(s=>'<option value="'+esc(s.id)+'">'+esc(s.book_title||s.filename)+'</option>').join('');$('empty-library').classList.toggle('hidden',sources.length>0);$('source-btn').disabled=!sources.length;}
function renderBook(d){$('book-title').textContent=d.book.title;$('book-description').textContent=d.book.description||'لا يوجد وصف متاح لهذا الكتاب بعد.';$('topic-count').textContent=d.topics.length+' محاور';$('material-count').textContent=d.count+' مواد';$('book-status').textContent=d.job?('الحالة: '+stageLabel(d.job.stage||d.job.status)):'جاهز للمراجعة';$('book-section').classList.remove('hidden');const kinds=new Set();const html=d.topics.map(t=>{const mats=t.materials.map(m=>{kinds.add(m.kind||'مادة');return '<button data-id="'+esc(m.id)+'" data-title="'+esc(m.title)+'" data-kind="'+esc(m.kind||'مادة')+'" data-content="'+esc(m.content)+'" data-position="'+m.position+'" class="material-card text-right rounded-2xl border bg-white p-4 hover:border-indigo-400"><div class="flex justify-between gap-3"><strong class="text-sm">'+esc(m.title)+'</strong><span class="text-xs text-slate-400">'+esc(m.kind||'مادة')+'</span></div><p class="mt-2 line-clamp-3 text-xs leading-6 text-slate-600">'+esc(m.content)+'</p><p class="mt-2 text-xs text-slate-400">'+esc(m.source_reference||'مرجع غير محدد')+'</p></button>';}).join('');return'<article data-topic class="rounded-2xl border bg-white p-5 shadow-sm"><button data-collapse class="flex w-full items-start justify-between gap-4 text-right"><div><p class="text-xs text-slate-400">المحور '+t.position+'</p><h3 class="mt-1 text-lg font-bold">'+esc(t.title)+'</h3><p class="mt-1 text-sm leading-6 text-slate-600">'+esc(t.description)+'</p></div><div class="text-left"><span class="rounded-full bg-indigo-50 px-3 py-1 text-xs text-indigo-700">'+t.materials.length+' مواد</span><p class="mt-2 text-xs text-slate-400">'+esc(t.discovery_status||'قيد التجهيز')+'</p></div></button><div data-topic-content class="mt-4 grid gap-3">'+(mats||'<p class="text-sm text-slate-400">لم تُكتشف مواد في هذا المحور حتى الآن.</p>')+'</div></article>';}).join('');$('topics').innerHTML=html;$('topics-empty').classList.toggle('hidden',d.topics.length>0);$('material-toolbar').classList.toggle('hidden',d.count===0);document.querySelectorAll('.material-card').forEach(b=>b.onclick=null);document.querySelectorAll('[data-collapse]').forEach(b=>b.onclick=()=>b.parentElement.querySelector('[data-topic-content]').classList.toggle('hidden'));populateKinds(kinds);applyMaterialFilters();}
function populateKinds(kinds){const select=$('material-kind');const current=select.value;select.innerHTML='<option value="">كل التصنيفات</option>'+Array.from(kinds).sort((a,b)=>a.localeCompare(b,'ar')).map(k=>'<option value="'+esc(k)+'">'+esc(k)+'</option>').join('');select.value=current;}
function applyMaterialFilters(){const query=$('material-search').value.trim().toLocaleLowerCase('ar');const kind=$('material-kind').value;const sort=$('material-sort').value;const cards=Array.from(document.querySelectorAll('.material-card'));cards.sort((a,b)=>{if(sort==='title')return a.dataset.title.localeCompare(b.dataset.title,'ar');if(sort==='kind')return a.dataset.kind.localeCompare(b.dataset.kind,'ar');return Number(a.dataset.position)-Number(b.dataset.position);});cards.forEach(card=>card.parentElement.appendChild(card));let visible=0;cards.forEach(card=>{const hay=(card.dataset.title+' '+card.dataset.content).toLocaleLowerCase('ar');const show=(!query||hay.includes(query))&&(!kind||card.dataset.kind===kind);card.classList.toggle('hidden',!show);if(show)visible++;});document.querySelectorAll('[data-topic]').forEach(topic=>topic.classList.toggle('hidden',topic.querySelectorAll('.material-card:not(.hidden)').length===0));$('material-result-count').textContent=visible+' من '+cards.length+' مواد معروضة';$('filtered-empty').classList.toggle('hidden',visible>0||cards.length===0);}
async function refreshBook(){if(!state.sourceId)return;try{renderBook(await request('/sources/'+state.sourceId+'/book-map'));}catch(e){showError('تعذر تحديث مساحة الكتاب الآن.');}}
async function poll(){if(!state.jobId)return;clearTimeout(state.pollTimer);try{const d=await request('/sources/'+state.sourceId+'/discovery/status');state.jobId=d.job_id||state.jobId;setStage(2);renderDiscoveryStatus(d);showProgress(stageLabel(d.stage),d.topics_completed||0,d.topics_total||0);await refreshBook();if(d.status==='COMPLETED'){showProgress('اكتمل تحليل الكتاب. الخريطة والمخزون جاهزان.',d.topics_total||1,d.topics_total||1);setBusy(false);$('start-discovery-btn')?.classList.add('hidden');return;}if(d.status==='FAILED'){setBusy(false);$('start-discovery-btn')?.classList.add('hidden');$('retry-box').classList.remove('hidden');showError('تعذر إكمال تحليل الكتاب. '+(d.error||'يمكنك إعادة المحاولة الآن.'));return;}if(d.status==='QUEUED'||d.status==='RUNNING')$('start-discovery-btn')?.classList.add('hidden');state.pollTimer=setTimeout(poll,2000);}catch(e){setBusy(false);showError(e.message);}}async function openBook(sourceId){clearError();clearTimeout(state.pollTimer);state.sourceId=sourceId;try{const book=await request('/sources/'+sourceId+'/book-map');renderBook(book);const status=await request('/sources/'+sourceId+'/discovery/status');state.jobId=status.job_id||null;renderDiscoveryStatus(status);if(status.status==='RUNNING'||status.status==='QUEUED'){setBusy(true);$('start-discovery-btn')?.classList.add('hidden');poll();}else{setBusy(false);$('start-discovery-btn')?.classList.toggle('hidden',status.status!=='NOT_STARTED');if(status.status==='FAILED')$('retry-box').classList.remove('hidden');}}catch(e){setBusy(false);showError(e.message);}}
function renderDiscoveryStatus(d){const box=$('discovery-status');if(!box)return;const cp=d.book_map_checkpoints||{};const total=cp.total||d.topics_total||0,done=cp.completed||d.topics_completed||0,pct=total?Math.min(100,Math.round(done/total*100)):d.status==='COMPLETED'?100:10;box.innerHTML='<div class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-xs font-bold text-indigo-600">حالة الفهم</p><p class="mt-1 font-bold">'+esc(stageLabel(d.stage||d.status))+'</p></div><div class="text-xs text-slate-500">المحاور '+(d.topics_completed||0)+' / '+(d.topics_total||0)+' · المقاطع '+(d.chunks_completed||0)+' / '+(d.chunks_total||0)+' · المواد '+(d.materials_discovered||0)+'</div></div><div class="mt-3 h-2 overflow-hidden rounded-full bg-slate-200"><div class="h-full bg-indigo-600 transition-all" style="width:'+pct+'%"></div></div><p class="mt-2 text-xs text-slate-500">المحور الحالي: '+esc(d.current_topic_id||'—')+' · المحاولة: '+(d.attempts||0)+(d.error_code?' · الخطأ: '+esc(d.error_code):'')+'</p>';}
async function startDiscovery(sourceId){if(!sourceId)return showError('اختر كتابًا محفوظًا أولًا.');clearError();clearTimeout(state.pollTimer);state.sourceId=sourceId;setBusy(true);$('start-discovery-btn')?.classList.add('hidden');showProgress('جاري بدء تحليل الكتاب...');try{const d=await request('/sources/'+sourceId+'/discovery',{method:'POST'});state.jobId=d.job_id||null;renderDiscoveryStatus(d);if(d.status==='COMPLETED'){setBusy(false);await refreshBook();showProgress('اكتمل تحليل الكتاب. الخريطة والمخزون جاهزان.');return;}showProgress(stageLabel(d.stage||d.status));poll();}catch(e){setBusy(false);$('start-discovery-btn')?.classList.remove('hidden');showError(e.message);}}
$('start-discovery-btn').onclick=()=>{if(state.sourceId)startDiscovery(state.sourceId);};
$('source-select').onchange=()=>{clearError();const id=$('source-select').value;if(id)openBook(id);else $('book-section').classList.add('hidden');};
$('source-btn').onclick=()=>{const id=$('source-select').value;if(!id)return showError('اختر كتابًا محفوظًا أولًا.');openBook(id);};
$('drop-zone').onclick=()=> $('pdf-file').click();$('drop-zone').onkeydown=e=>{if(e.key==='Enter'||e.key===' ')$('pdf-file').click();};$('drop-zone').ondragover=e=>{e.preventDefault();$('drop-zone').classList.add('dragging');};$('drop-zone').ondragleave=()=>$('drop-zone').classList.remove('dragging');$('drop-zone').ondrop=e=>{e.preventDefault();$('drop-zone').classList.remove('dragging');if(e.dataTransfer.files.length){$('pdf-file').files=e.dataTransfer.files;$('pdf-file').dispatchEvent(new Event('change'));}};$('pdf-file').onchange=()=>{const file=$('pdf-file').files[0];$('file-name').classList.toggle('hidden',!file);if(file)$('file-name').textContent=file.name+' — '+(file.size/1024/1024).toFixed(1)+' MB';};
$('upload-btn').onclick=async()=>{clearError();const file=$('pdf-file').files[0];if(!file)return showError('اختر ملف PDF أولًا.');if(file.type!=='application/pdf'&&!file.name.toLowerCase().endsWith('.pdf'))return showError('الملف المحدد ليس بصيغة PDF.');if(file.size>100*1024*1024)return showError('حجم الملف يتجاوز الحد الأقصى وهو 100 MB.');setBusy(true);showProgress('جاري رفع الكتاب وحفظه...');try{const form=new FormData();form.append('file',file);const s=await request('/sources',{method:'POST',body:form});await loadSources();$('source-select').value=s.id;await openBook(s.id);setBusy(false);$('start-discovery-btn')?.classList.remove('hidden');showProgress('تم حفظ الكتاب. ابدأ التحليل من مساحة الكتاب.');}catch(e){setBusy(false);showError(e.message);}};
$('retry-btn').onclick=()=>{if(state.sourceId)startRetry();};async function startRetry(){clearError();setBusy(true);showProgress('جاري استئناف تحليل الكتاب...');try{const d=await request('/sources/'+state.sourceId+'/discovery/retry',{method:'POST'});state.jobId=d.job_id||null;poll();}catch(e){setBusy(false);showError(e.message);}}

$('material-search').oninput=applyMaterialFilters;$('material-kind').onchange=applyMaterialFilters;$('material-sort').onchange=applyMaterialFilters;$('clear-material-filters').onclick=()=>{$('material-search').value='';$('material-kind').value='';$('material-sort').value='position';applyMaterialFilters();};$('collapse-topics').onclick=()=>{const topics=Array.from(document.querySelectorAll('[data-topic-content]'));const shouldOpen=topics.some(x=>!x.classList.contains('hidden'));topics.forEach(x=>x.classList.toggle('hidden',shouldOpen));$('collapse-topics').textContent=shouldOpen?'فتح المحاور':'طيّ المحاور';};$('refresh-btn').onclick=()=>{if(state.sourceId)openBook(state.sourceId);};loadSources().catch(e=>showError(e.message));
</script></body></html>'''
